project:
  type: website
  output-dir: docs

website:
  title: "League Name Dingers Only"
  navbar: false

format:
  html:
    theme: darkly
    css: styles.css
    toc: false
    smooth-scroll: true

execute:
  echo: false
  warning: false
  message: false